# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_student'),
        ('contacts', '0004_auto_20171104_0959'),
    ]

    operations = [
    ]
