# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_merge_20171104_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
