# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20171104_1407'),
        ('contacts', '0008_communicationrecord_donor'),
    ]

    operations = [
    ]
