# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_merge_20171104_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='contact',
        ),
    ]
