# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20171104_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='referral',
            field=models.CharField(blank=True, choices=[('From a Friend', 'From a Friend'), ('Posted Notice', 'Posted Notice'), ('Newsletter', 'Newsletter'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ways_to_help',
            field=models.CharField(blank=True, choices=[('Fundraising', 'Fundraising'), ('Usering/Staffing Events', 'Usering/Staffing Events'), ('Serving on the Board of Directors', 'Serving on the Board of Directors'), ('Coordinating Sepcial Events', 'Coordinating Sepcial Events'), ('Assist in Dance Class', 'Assist in Dance Class'), ('Assist in Music Class', 'Assist in Music Class'), ('Assist in Arts Class', 'Assist in Arts Class'), ('Serve on Committee', 'Serve on Committee'), ('Office Assistance', 'Office Assistance'), ('Technical Support', 'Technical Support'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
