# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20171104_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='kind',
        ),
    ]
