# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20171104_1448'),
        ('contacts', '0012_remove_contact_kind'),
    ]

    operations = [
    ]
