# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_remove_record_person'),
        ('forms', '0003_remove_form_person'),
        ('contacts', '0013_merge_20171104_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Phone', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signed_up_date', models.DateField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=10)),
                ('mid', models.CharField(blank=True, max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Phone', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signed_up_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='emergency_contact',
        ),
        migrations.DeleteModel(
            name='ContactType',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='contact',
        ),
        migrations.AlterField(
            model_name='communicationrecord',
            name='external_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual'),
        ),
        migrations.AlterField(
            model_name='communicationrecord',
            name='internal_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_contact', to='contacts.Individual'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Organization'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='communicationrecord',
            name='external_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Organization'),
        ),
        migrations.AddField(
            model_name='donor',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual'),
        ),
    ]
