# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_remove_donor_donor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='individual',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='contact',
            new_name='individual',
        ),
        migrations.AddField(
            model_name='individual',
            name='is_donor',
            field=models.BooleanField(default=False, verbose_name='Is Donor'),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Is Student'),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_volunteer',
            field=models.BooleanField(default=False, verbose_name='Is Volunteer'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
    ]
