# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20171104_2116'),
        ('contacts', '0018_auto_20171104_2134'),
    ]

    operations = [
    ]
