# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_volunteer_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ways_to_help', models.CharField(blank=True, choices=[('Sewing Costumes', 'Sewing Costumes'), ('Transportation', 'Transportation'), ('Snacks', 'Snacks'), ('Set Decoration', 'Set Decoration'), ('On-Stage Assistance', 'On-Stage Assistance'), ('Ad Sales', 'Ad Sales'), ('Other', 'Other')], max_length=50, null=True)),
            ],
        ),
    ]
