# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_volunteer_event'),
        ('contacts', '0019_merge_20171104_2143'),
    ]

    operations = [
    ]
