# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Guardian'),
        ),
    ]
