# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20171104_2207'),
        ('contacts', '0021_auto_20171104_2209'),
    ]

    operations = [
    ]
