# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_auto_20171104_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='event',
            new_name='events',
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='classes.Class'),
        ),
    ]
