# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_auto_20171104_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_artist',
            field=models.BooleanField(default=False, verbose_name='Artist?'),
        ),
    ]
