# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_individual_is_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_board',
            field=models.BooleanField(default=False, verbose_name='Board Member?'),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff?'),
        ),
    ]
