# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_individual_is_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaysToHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_to_help', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='ways_to_help',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ways_to_help',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.WaysToHelp'),
        ),
    ]
