# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_auto_20171105_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='ways_to_help',
            field=models.ManyToManyField(to='contacts.WaysToHelp'),
        ),
    ]
