# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_auto_20171105_1102'),
        ('contacts', '0029_auto_20171105_1058'),
    ]

    operations = [
    ]
