# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_merge_20171105_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ways_to_help',
            field=models.ManyToManyField(blank=True, to='contacts.WaysToHelp'),
        ),
    ]
