# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_auto_20171105_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='contacts.Individual', verbose_name='Individual contacts'),
        ),
    ]
