# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0033_organization_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='contact_method',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('SMS', 'SMS')], default='Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_method',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('SMS', 'SMS')], default='Phone', max_length=20),
        ),
    ]
