# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_auto_20171106_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='second_street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='second_street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
