# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0013_merge_20171104_1720'),
        ('events', '0002_auto_20171104_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('In Kind', 'In Kind'), ('Cash', 'Cash'), ('Website', 'Website'), ('Check', 'Check'), ('Credit Card', 'Credit Card')], max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Donor')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
