# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
