# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20171105_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
