# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171104_0959'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('background_check', 'Background Check'), ('enrollment_form', 'Enrollment Form'), ('volunteer_form', 'Volunteer Form'), ('other', 'Other')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='is_filled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
            preserve_default=False,
        ),
    ]
