# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171103_2252'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='formType',
            field=models.CharField(choices=[('background_check', 'Background Check'), ('enrollment_form', 'Enrollment Form'), ('volunteer_form', 'Volunteer Form')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='isFilled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='lastEdited',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='notes',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.Person'),
            preserve_default=False,
        ),
    ]
