# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20171104_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='person',
        ),
    ]
