# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20171103_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='formType',
            field=models.CharField(choices=[('background_check', 'Background Check'), ('enrollment_form', 'Enrollment Form'), ('volunteer_form', 'Volunteer Form'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='lastEdited',
            field=models.DateField(auto_now=True),
        ),
    ]
