# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20171103_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
