# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_individual_is_artist'),
        ('forms', '0006_remove_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_filled', models.BooleanField()),
                ('date', models.DateField()),
                ('last_edited', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='is_filled',
        ),
        migrations.RemoveField(
            model_name='form',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='form',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='form',
            name='person',
        ),
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='FormType',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Individual'),
        ),
    ]
