# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20171105_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='form_type',
            new_name='form_name',
        ),
    ]
