# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171103_2252'),
        ('time_tracker', '0002_auto_20171104_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='timetracker',
            name='person',
        ),
        migrations.DeleteModel(
            name='TimeTracker',
        ),
    ]
