# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171104_1737'),
        ('classes', '0001_initial'),
        ('time_tracker', '0003_record_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='class_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.AddField(
            model_name='record',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
